name: Build & Deploy Backend (GHCR)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build JAR (Gradle)
        run: |
          ./gradlew clean bootJar -x test

      - name: Login to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/Dlelo/marketplace-backend:latest -t ghcr.io/Dlelo/marketplace-backend:${{ github.sha }} .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/Dlelo/marketplace-backend:latest
          docker push ghcr.io/Dlelo/marketplace-backend:${{ github.sha }}

      - name: Deploy to server (pull & restart)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DOSSH }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose pull backend
            docker compose up -d --no-deps --build backend
            docker compose restart nginx
